import pyautogui
import time
import webbrowser

# فتح المتصفح والذهاب إلى GitHub
webbrowser.open('https://github.com/login')

# الانتظار حتى يتم تحميل الصفحة
time.sleep(3)

# كتابة اسم المستخدم (استبدل بقيمتك)
pyautogui.write('YourUsername')  # استبدل بـ اسم المستخدم الخاص بك
pyautogui.press('tab')  # الانتقال إلى حقل كلمة المرور

# كتابة كلمة المرور (استبدل بقيمتك)
pyautogui.write('YourPassword')  # استبدل بكلمة المرور الخاصة بك
pyautogui.press('enter')  # الضغط على زر الدخول
