import pyautogui
import time

# انتظر قليلاً قبل تنفيذ الإجراءات
time.sleep(2)

# فتح نافذة RDP
pyautogui.hotkey('win', 'r')  # اختصار لفتح نافذة "تشغيل"
pyautogui.write('mstsc')
pyautogui.press('enter')

# الانتظار حتى تظهر نافذة RDP
time.sleep(2)

# إدخال عنوان الـ IP أو اسم الكمبيوتر
pyautogui.write('192.168.1.100')  # استبدل بـ عنوان IP للجهاز البعيد
pyautogui.press('tab')  # الانتقال إلى حقل اسم المستخدم

# إدخال اسم المستخدم
pyautogui.write('YourUsername')  # استبدل باسم المستخدم الخاص بك
pyautogui.press('tab')  # الانتقال إلى حقل كلمة المرور

# إدخال كلمة المرور
pyautogui.write('YourPassword')  # استبدل بكلمة المرور
pyautogui.press('enter')  # الضغط على Enter لتسجيل الدخول
